### ISSUE TITLE
Publicering och licens

### ISSUE THREAD

**Issue by larsnystrom** [Lundakarnevalen/futural-extern-android#6]
Som ni kanske märkt har jag gjort ett par repositories publika för Lundakarnevalen. De som hittills är publika är de som bara jag har jobbat med.

Efter karnevalen är min ambition att vi ska kunna publicera fler repos, bland annat detta. Jag tänker mig att vi gör det under en MIT-licens, men jag vill inte göra det utan att ni är okej med det.

Därför undrar jag om det är någon som har några invändningar mot att jag publicerar detta repo med en MIT-licens efter karnevalen, dvs efter 18 maj 2014? Ni får gärna fundera en vända över eventuella problem ni ser med det och framför allt
- Säkerhetsrisker
- Licenskompatabilitet med tredjepartsmjukvara

Jag har säkert glömt att tänka på något, så vi för en diskussion här innan några beslut fattas.

**Comment by larsnystrom** [comment]
Done.

**Comment by tkhduracell** [comment]
@larsnystrom Skjuter du in LICENSE.md in repona också?

**Comment by larsnystrom** [comment]
Äh, jag tar en MIT-licens och skriver in namnet på alla som har committat till respektive repo enligt github med 2014 som år. Fixar det nu :+1:

**Comment by xeloader** [comment]
Blir suuuper!

**Comment by alexandernajafi** [comment]
blir superbra! Vet någon om karnevalen nästa år kommer använda våra grejer?
Vi kanske borde berätta för dem att det finns i all fall :)

2016-11-09 21:11 GMT+01:00 Victor Ingman <notifications@github.com>:

**Comment by larsnystrom** [comment]
Jag kommer nog ha någon typ av överlämning med min efterträdare :)
